/* autogenerated jconfig.h based on Android.mk var JCONFIG_FLAGS */ 
#ifndef JPEG_LIB_VERSION
#define JPEG_LIB_VERSION 62
#endif

#ifndef LIBJPEG_TURBO_VERSION
#define LIBJPEG_TURBO_VERSION 2.0.2
#endif

#ifndef LIBJPEG_TURBO_VERSION_NUMBER
#define LIBJPEG_TURBO_VERSION_NUMBER 202
#endif

#ifndef C_ARITH_CODING_SUPPORTED
#define C_ARITH_CODING_SUPPORTED
#endif

#ifndef D_ARITH_CODING_SUPPORTED
#define D_ARITH_CODING_SUPPORTED
#endif

#ifndef MEM_SRCDST_SUPPORTED
#define MEM_SRCDST_SUPPORTED
#endif

#ifndef WITH_SIMD
#define WITH_SIMD
#endif

#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE 8
#endif

#ifndef HAVE_LOCALE_H
#define HAVE_LOCALE_H
#endif

#ifndef HAVE_STDDEF_H
#define HAVE_STDDEF_H
#endif

#ifndef HAVE_STDLIB_H
#define HAVE_STDLIB_H
#endif

#ifndef NEED_SYS_TYPES_H
#define NEED_SYS_TYPES_H
#endif

#ifndef HAVE_UNSIGNED_CHAR
#define HAVE_UNSIGNED_CHAR
#endif

#ifndef HAVE_UNSIGNED_SHORT
#define HAVE_UNSIGNED_SHORT
#endif

