/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_AppDataDir */

#ifndef _Included_magick_AppDataDir
#define _Included_magick_AppDataDir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_Magick
 * Method:    setAppConfigDataDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_Magick_setAppConfigDataDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
