/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_Cache */

#ifndef _Included_magick_Cache
#define _Included_magick_Cache
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     magick_Magick
 * Method:    setCacheDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_Magick_setCacheDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
