/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_MagickInfo */

#ifndef _Included_magick_MagickInfo
#define _Included_magick_MagickInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_MagickInfo
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MagickInfo_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MagickInfo
 * Method:    destroyMagickInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_MagickInfo_destroyMagickInfo
  (JNIEnv *, jobject);

/*
 * Class:     magick_MagickInfo
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MagickInfo_getDescription
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
