/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_MontageInfo */

#ifndef _Included_magick_MontageInfo
#define _Included_magick_MontageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_MontageInfo
 * Method:    init
 * Signature: (Lmagick/ImageInfo;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    destroyMontageInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_destroyMontageInfo
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setGeometry
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setGeometry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getGeometry
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getGeometry
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setTile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setTile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getTile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getTile
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setFrame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setFrame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getFrame
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getFrame
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setTexture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setTexture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getTexture
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getTexture
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setFont
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getFont
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getFont
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setPointSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setPointSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_MontageInfo
 * Method:    getPointSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_MontageInfo_getPointSize
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setBorderWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setBorderWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_MontageInfo
 * Method:    getBorderWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_MontageInfo_getBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setGravity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setGravity
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_MontageInfo
 * Method:    getGravity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_MontageInfo_getGravity
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setShadow
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setShadow
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     magick_MontageInfo
 * Method:    getShadow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_MontageInfo_getShadow
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setFill
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setFill
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    getFill
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_MontageInfo_getFill
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setStroke
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setStroke
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    getStroke
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_MontageInfo_getStroke
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setBackgroundColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setBackgroundColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    getBackgroundColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_MontageInfo_getBackgroundColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setBorderColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setBorderColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    getBorderColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_MontageInfo_getBorderColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setMatteColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setMatteColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    getMatteColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_MontageInfo_getMatteColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_MontageInfo
 * Method:    setFileName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_MontageInfo_setFileName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_MontageInfo
 * Method:    getFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_MontageInfo_getFileName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
