/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_MagickImage */

#ifndef _Included_magick_Morphology
#define _Included_magick_Morphology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_MagickImage
 * Method:    morphologyImageInternal
 * Signature: (IILjava/lang/String;)Lmagick/MagickImage;
 */
JNIEXPORT jobject JNICALL Java_magick_MagickImage_morphologyImageInternal
  (JNIEnv *, jobject, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
