/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_ImageInfo */

#ifndef _Included_magick_ImageInfo
#define _Included_magick_ImageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_ImageInfo
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_init
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setFileName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setFileName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    setImageOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setImageOption
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getFileName
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setAffirm
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setAffirm
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     magick_ImageInfo
 * Method:    getAffirm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_ImageInfo_getAffirm
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setSubimage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setSubimage
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getSubimage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getSubimage
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setSubrange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setSubrange
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getSubrange
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getSubrange
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setServerName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setServerName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getServerName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getServerName
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setFont
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getFont
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getFont
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setSize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getSize
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getSize
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setTile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setTile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getTile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getTile
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setDensity
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setDensity
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getDensity
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getDensity
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setPage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setPage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getPage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getPage
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setTexture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setTexture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getTexture
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getTexture
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setView
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setView
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getView
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getView
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setAdjoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setAdjoin
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getAdjoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getAdjoin
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setColorspace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setColorspace
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getColorspace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getColorspace
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setCompression
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setCompression
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getCompression
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getCompression
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setDither
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setDither
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getDither
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getDither
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setAntialias
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setAntialias
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getAntialias
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getAntialias
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setInterlace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setInterlace
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getInterlace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getInterlace
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setMonochrome
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setMonochrome
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getMonochrome
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getMonochrome
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setFuzz
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setFuzz
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_ImageInfo
 * Method:    getFuzz
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_ImageInfo_getFuzz
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setPointSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setPointSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getPointSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getPointSize
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setQuality
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setQuality
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getQuality
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getQuality
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setVerbose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setVerbose
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getVerbose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getVerbose
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setPreviewType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setPreviewType
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getPreviewType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getPreviewType
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setPing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setPing
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     magick_ImageInfo
 * Method:    getPing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_ImageInfo_getPing
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    destroyImageInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_destroyImageInfo
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setMagick
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setMagick
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_ImageInfo
 * Method:    getMagick
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_ImageInfo_getMagick
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setUnits
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setUnits
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_ImageInfo
 * Method:    getUnits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getUnits
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setBorderColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setBorderColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    getBorderColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_ImageInfo_getBorderColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    getDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_ImageInfo_getDepth
  (JNIEnv *, jobject);

/*
 * Class:     magick_ImageInfo
 * Method:    setDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_ImageInfo_setDepth
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
