/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_DrawInfo */

#ifndef _Included_magick_DrawInfo
#define _Included_magick_DrawInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_DrawInfo
 * Method:    init
 * Signature: (Lmagick/ImageInfo;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    destroyDrawInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_destroyDrawInfo
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setPrimitive
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setPrimitive
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_DrawInfo
 * Method:    getPrimitive
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_DrawInfo_getPrimitive
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_DrawInfo_getText
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_DrawInfo
 * Method:    getGeometry
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_DrawInfo_getGeometry
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setGeometry
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setGeometry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_DrawInfo
 * Method:    setFont
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     magick_DrawInfo
 * Method:    getFont
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_magick_DrawInfo_getFont
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setStrokeAntialias
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setStrokeAntialias
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     magick_DrawInfo
 * Method:    getStrokeAntialias
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_DrawInfo_getStrokeAntialias
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setTextAntialias
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setTextAntialias
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     magick_DrawInfo
 * Method:    getTextAntialias
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_DrawInfo_getTextAntialias
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setGravity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setGravity
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_DrawInfo
 * Method:    getGravity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_DrawInfo_getGravity
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setOpacity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setOpacity
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_DrawInfo
 * Method:    getOpacity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_DrawInfo_getOpacity
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setDecorate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setDecorate
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_DrawInfo
 * Method:    getDecorate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_DrawInfo_getDecorate
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setKerning
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setKerning
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_DrawInfo
 * Method:    getKerning
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_DrawInfo_getKerning
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setInterwordSpacing
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setInterwordSpacing
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_DrawInfo
 * Method:    getInterwordSpacing
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_DrawInfo_getInterwordSpacing
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setInterlineSpacing
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setInterlineSpacing
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_DrawInfo
 * Method:    getInterlineSpacing
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_DrawInfo_getInterlineSpacing
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setStrokeWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setStrokeWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_DrawInfo
 * Method:    getStrokeWidth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_DrawInfo_getStrokeWidth
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setPointsize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setPointsize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     magick_DrawInfo
 * Method:    getPointsize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_magick_DrawInfo_getPointsize
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setFill
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setFill
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getFill
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_DrawInfo_getFill
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setStroke
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setStroke
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getStroke
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_DrawInfo_getStroke
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setUnderColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setUnderColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getUnderColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_DrawInfo_getUnderColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setBorderColor
 * Signature: (Lmagick/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setBorderColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getBorderColor
 * Signature: ()Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_DrawInfo_getBorderColor
  (JNIEnv *, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    setTile
 * Signature: (Lmagick/MagickImage;)V
 */
JNIEXPORT void JNICALL Java_magick_DrawInfo_setTile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     magick_DrawInfo
 * Method:    getTile
 * Signature: ()Lmagick/MagickImage;
 */
JNIEXPORT jobject JNICALL Java_magick_DrawInfo_getTile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
