/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_QuantizeInfo */

#ifndef _Included_magick_QuantizeInfo
#define _Included_magick_QuantizeInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_QuantizeInfo
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_init
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    destroyQuantizeInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_destroyQuantizeInfo
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    setNumberColors
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_setNumberColors
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_QuantizeInfo
 * Method:    getNumberColors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_QuantizeInfo_getNumberColors
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    setTreeDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_setTreeDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_QuantizeInfo
 * Method:    getTreeDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_QuantizeInfo_getTreeDepth
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    setDither
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_setDither
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_QuantizeInfo
 * Method:    getDither
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_QuantizeInfo_getDither
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    setColorspace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_setColorspace
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_QuantizeInfo
 * Method:    getColorspace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_QuantizeInfo_getColorspace
  (JNIEnv *, jobject);

/*
 * Class:     magick_QuantizeInfo
 * Method:    setMeasureError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_magick_QuantizeInfo_setMeasureError
  (JNIEnv *, jobject, jint);

/*
 * Class:     magick_QuantizeInfo
 * Method:    getMeasureError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_magick_QuantizeInfo_getMeasureError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
