/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_Channel */

#ifndef _Included_magick_Channel
#define _Included_magick_Channel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_MagickImage
 * Method:    getImageAlphaChannel
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_magick_MagickImage_getImageAlphaChannel
  (JNIEnv *, jobject);

/*
 * Class:     magick_MagickImage
 * Method:    setImageAlphaChannel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_magick_MagickImage_setImageAlphaChannel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
