/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_PixelPacket */

#ifndef _Included_magick_PixelPacket
#define _Included_magick_PixelPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_PixelPacket
 * Method:    queryColorDatabase
 * Signature: (Ljava/lang/String;)Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_PixelPacket_queryColorDatabase
  (JNIEnv *, jclass, jstring);

/*
 * Class:     magick_PixelPacket
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Lmagick/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_magick_PixelPacket_getColor
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
