/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class magick_ICUDataDir */

#ifndef _Included_magick_ICUDataDir
#define _Included_magick_ICUDataDir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     magick_Magick
 * Method:    setICUDataDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_magick_Magick_setICUDataDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
